### ISSUE TITLE
Prefix url not found

### ISSUE THREAD

**Issue by ExsyDev** [akaunting/laravel-language#30]
Hello. I have enabled property url in config. When I go to site: `site.com/en/` or `site.com/de/` I get 404. Why? And when I change language, I get wrong path like this: `site.com/back/ite.com`

My code of language switcher:

```
@foreach (language()->allowed() as $code => $name)
    <a href="{{ language()->back($code) }}">{{ $name }}</a>
@endforeach
```

**Comment by nagi1** [comment]
does anyone find the issue here ?

**Comment by RomkaLTU** [comment]
Same here. Couldn't get this package to work. 

```
Route::group(['middleware' => 'language'], function() {
    Route::get('doctors/{doctor}', ['App\Http\Controllers\DoctorController', 'show'])->name('doctor');
});
```

Clicking on the language link redirects omitting "/doctors/" part and 404
Tried session and referee strategy. Honestly don't understand how this plugin works.
