### ISSUE TITLE
change controller and middleware dir

### ISSUE THREAD

**Issue by robel93** [akaunting/laravel-language#31]
I have made some changes in your controllers and your middleware so i have copied them to my own controller and middleware folder and then via config/language.php i want to redirect to the copied middleware and controller but it seem not to find my copied middleware/controller. Is this even possible if so how? i know this might be an question more than a issue but iam new to programming an would appreciate some help. I have tried using the base_path('app/http/controll...) function but i get an error stating the file could not be found

**Comment by gtamborero** [comment]
Please explain better your problem :)

**Comment by robel93** [comment]
In config/language.php i want to change the direction of following variable...

 /*
    |--------------------------------------------------------------------------
    | Middleware
    |--------------------------------------------------------------------------
    |
    | This option indicates the middleware to change language.
    |
    */
    'middleware'    => 'Akaunting\Language\Middleware\SetLocale',

    /*
    |--------------------------------------------------------------------------
    | Controller
    |--------------------------------------------------------------------------
    |
    | This option indicates the controller to be used.
    |
    */
    'controller'    => 'Akaunting\Language\Controllers\Language',


My controller and middleware i want to use are in app/http/controller and app/http/controller but when i change the controller/middleware directory in the config file it cant find the file

**Comment by gtamborero** [comment]
Did you install the package with composer as on the doc's is mentioned? you should:
https://github.com/akaunting/language
command line: composer require akaunting/language

**Comment by robel93** [comment]
Yes i have done this already. Dont think you understand my problem i will try to explain again :)

So i have implemented akaunting/language and it works just fine. But i did manually do some code changes in both 

vendor\akaunting\language\src\Middleware\SetLocale.php

and

vendor\akaunting\language\src\Controllers\Language.php

The problem now whenever i do an 'composer install' again(This command is done every time i deploy) my updated code is overriten. So i want to solve this problem by copy the middleware and controller with my code updates and change there destination to...

app\Http\Middleware\SetLocale.php

and

app\Http\Controllers\Language.php

To do this i need to update 2 variables that is shown in previous comment but when i change to my new directories it cant find the files

**Comment by gtamborero** [comment]
Thanks! I understand. I supose that your problem is not with this package but with laravel and I'm also not sure if your way of altering the code is correct...
Try:
    'middleware'    => '\App\Http\Middleware\SetLocale',

**Comment by robel93** [comment]
i still get 


ReflectionException (-1)
Class App\Http\Controllers\Language does not exist
